services:
  db:
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432/tcp
    environment:
      LANG: en_US.UTF-8
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  memcached:
    image: memcached:latest
    restart: on-failure
    ports:
      - 12345:11211/tcp
    command: memcached -m 1024m
#  mongo:
#    image: mongo
#    restart: on-failure
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  nginx:
    image: nginx:latest
    restart: on-failure
    ports:
      - 80:80/tcp
    depends_on:
      - web
    links:
      - web
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
      - ${NGINX_MEDIA_PATH}:/media
      - ${NGINX_STATIC_PATH}:/static
  web:
    build: .
    restart: on-failure
    user: 1000:1000
    command: bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh db:5432 -t 0 && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn djangoutils.wsgi:application -w 2 -b 0.0.0.0:8080 --reload"
    volumes:
      - ${CODE_PATH}:/code
    ports:
      - 8080:8080/tcp
    depends_on:
      - db
      - memcached
    links:
      - db
      - memcached
    env_file:
      - .env
